[project]
name = "faers-datalakehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks-connect>=17.2.0",
    "ruff>=0.13.1",
]
