name: Deploy Infrastructure
on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/main_infrastructure.yml"

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy Infrastructure to Development
        working-directory: infra/terraform
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          TF_VAR_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        run: |
          terraform init -backend-config="storage_account_name=faerslakehouse" 
          terraform apply -auto-approve 
          echo "✅ Successfully deployed infrastructure to development environment"
