name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      BUNDLE_databricks_host: ${{ secrets.DATABRICKS_HOST }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests
        run: |
          uv run ruff check .
          uv run ruff format --check .
          uv run pytest tests/ -v

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks bundle

        run: databricks bundle validate --target dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Validate Terraform
        working-directory: infra/terraform
        run: |
          terraform init -backend=false
          terraform validate
